/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : string,
  'title' : string,
  'description' : string,
  'imageUrl' : string,
}
export interface Config {
  'categories' : Array<Category>,
  'heroDescription' : string,
  'brandName' : string,
  'heroHeadline' : string,
}
export interface Order {
  'id' : string,
  'lineItems' : Array<OrderLineItem>,
  'buyerEmail' : string,
  'totalAmount' : bigint,
  'currency' : string,
  'timestamp' : Time,
  'shippingAddress' : string,
  'buyerName' : string,
}
export interface OrderLineItem {
  'color' : [] | [string],
  'size' : [] | [string],
  'productId' : string,
  'quantity' : bigint,
}
export interface Product {
  'id' : string,
  'categoryId' : string,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'sizes' : Array<string>,
  'stockCount' : bigint,
  'imageUrl' : string,
  'currency' : string,
  'colors' : Array<string>,
  'price' : bigint,
  'styleTags' : Array<RegionStyle>,
}
export type RegionStyle = { 'southAmerican' : null } |
  { 'european' : null } |
  { 'australian' : null } |
  { 'italian' : null } |
  { 'american' : null } |
  { 'canadian' : null };
export type Time = bigint;
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [
      string,
      string,
      bigint,
      string,
      string,
      string,
      Array<string>,
      Array<string>,
      bigint,
      Array<RegionStyle>,
    ],
    string
  >,
  'getAllOrders' : ActorMethod<[], Array<[string, Order]>>,
  'getConfig' : ActorMethod<[], Config>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getProductsByStyle' : ActorMethod<[RegionStyle], Array<Product>>,
  'placeOrder' : ActorMethod<
    [string, string, string, Array<OrderLineItem>, string],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];