/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const Config = IDL.Record({
  'categories' : IDL.Vec(Category),
  'heroDescription' : IDL.Text,
  'brandName' : IDL.Text,
  'heroHeadline' : IDL.Text,
});

export const idlService = IDL.Service({
  'getConfig' : IDL.Func([], [Config], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const Config = IDL.Record({
    'categories' : IDL.Vec(Category),
    'heroDescription' : IDL.Text,
    'brandName' : IDL.Text,
    'heroHeadline' : IDL.Text,
  });
  
  return IDL.Service({ 'getConfig' : IDL.Func([], [Config], []) });
};

export const init = ({ IDL }) => { return []; };