/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Category {
    id: string;
    title: string;
    description: string;
    imageUrl: string;
}
export interface Config {
    categories: Array<Category>;
    heroDescription: string;
    brandName: string;
    heroHeadline: string;
}
export interface Product {
    id: string;
    categoryId: string;
    inStock: boolean;
    name: string;
    description: string;
    sizes: Array<string>;
    stockCount: bigint;
    imageUrl: string;
    currency: string;
    colors: Array<string>;
    price: bigint;
    styleTags: Array<RegionStyle>;
}
export interface OrderLineItem {
    color?: string;
    size?: string;
    productId: string;
    quantity: bigint;
}
export enum RegionStyle {
    southAmerican = "southAmerican",
    european = "european",
    australian = "australian",
    italian = "italian",
    american = "american",
    canadian = "canadian"
}
export interface backendInterface {
    addProduct(name: string, description: string, price: bigint, currency: string, categoryId: string, imageUrl: string, sizes: Array<string>, colors: Array<string>, stockCount: bigint, styleTags: Array<RegionStyle>): Promise<string>;
    getAllProducts(): Promise<Array<Product>>;
    getConfig(): Promise<Config>;
    getProduct(productId: string): Promise<Product | null>;
    getProductsByCategory(categoryId: string): Promise<Array<Product>>;
    getProductsByStyle(styleFilter: RegionStyle): Promise<Array<Product>>;
    placeOrder(buyerName: string, buyerEmail: string, shippingAddress: string, lineItems: Array<OrderLineItem>, currency: string): Promise<string>;
}
import type { OrderLineItem as _OrderLineItem, Product as _Product, RegionStyle as _RegionStyle } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addProduct(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string, arg5: string, arg6: Array<string>, arg7: Array<string>, arg8: bigint, arg9: Array<RegionStyle>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg9));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg9));
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConfig(): Promise<Config> {
        if (this.processError) {
            try {
                const result = await this.actor.getConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConfig();
            return result;
        }
    }
    async getProduct(arg0: string): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByStyle(arg0: RegionStyle): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByStyle(to_candid_RegionStyle_n2(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByStyle(to_candid_RegionStyle_n2(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: string, arg1: string, arg2: string, arg3: Array<OrderLineItem>, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1, arg2, to_candid_vec_n11(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1, arg2, to_candid_vec_n11(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
}
function from_candid_Product_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_RegionStyle_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegionStyle): RegionStyle {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categoryId: string;
    inStock: boolean;
    name: string;
    description: string;
    sizes: Array<string>;
    stockCount: bigint;
    imageUrl: string;
    currency: string;
    colors: Array<string>;
    price: bigint;
    styleTags: Array<_RegionStyle>;
}): {
    id: string;
    categoryId: string;
    inStock: boolean;
    name: string;
    description: string;
    sizes: Array<string>;
    stockCount: bigint;
    imageUrl: string;
    currency: string;
    colors: Array<string>;
    price: bigint;
    styleTags: Array<RegionStyle>;
} {
    return {
        id: value.id,
        categoryId: value.categoryId,
        inStock: value.inStock,
        name: value.name,
        description: value.description,
        sizes: value.sizes,
        stockCount: value.stockCount,
        imageUrl: value.imageUrl,
        currency: value.currency,
        colors: value.colors,
        price: value.price,
        styleTags: from_candid_vec_n7(_uploadFile, _downloadFile, value.styleTags)
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    southAmerican: null;
} | {
    european: null;
} | {
    australian: null;
} | {
    italian: null;
} | {
    american: null;
} | {
    canadian: null;
}): RegionStyle {
    return "southAmerican" in value ? RegionStyle.southAmerican : "european" in value ? RegionStyle.european : "australian" in value ? RegionStyle.australian : "italian" in value ? RegionStyle.italian : "american" in value ? RegionStyle.american : "canadian" in value ? RegionStyle.canadian : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RegionStyle>): Array<RegionStyle> {
    return value.map((x)=>from_candid_RegionStyle_n8(_uploadFile, _downloadFile, x));
}
function to_candid_OrderLineItem_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderLineItem): _OrderLineItem {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_RegionStyle_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegionStyle): _RegionStyle {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    color?: string;
    size?: string;
    productId: string;
    quantity: bigint;
}): {
    color: [] | [string];
    size: [] | [string];
    productId: string;
    quantity: bigint;
} {
    return {
        color: value.color ? candid_some(value.color) : candid_none(),
        size: value.size ? candid_some(value.size) : candid_none(),
        productId: value.productId,
        quantity: value.quantity
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegionStyle): {
    southAmerican: null;
} | {
    european: null;
} | {
    australian: null;
} | {
    italian: null;
} | {
    american: null;
} | {
    canadian: null;
} {
    return value == RegionStyle.southAmerican ? {
        southAmerican: null
    } : value == RegionStyle.european ? {
        european: null
    } : value == RegionStyle.australian ? {
        australian: null
    } : value == RegionStyle.italian ? {
        italian: null
    } : value == RegionStyle.american ? {
        american: null
    } : value == RegionStyle.canadian ? {
        canadian: null
    } : value;
}
function to_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<RegionStyle>): Array<_RegionStyle> {
    return value.map((x)=>to_candid_RegionStyle_n2(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<OrderLineItem>): Array<_OrderLineItem> {
    return value.map((x)=>to_candid_OrderLineItem_n12(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
